version: "3.7"
services:
  mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all","--replSet", "rs"]
  node:
    build: './dronesym-node'
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/dronesym
  angular:
    build: './dronesym-frontend'
    ports:
      - "4200:4200"
  flask:
    build: './dronesym-python'
    ports:
      - "5000:5000"
  
